sudo:
  - false
language:
  - python
python:
  - '3.6'
  - '3.5'
  - '2.7'
cache:
  - pip
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=./
after_success:
  - bash < (curl -s https://codecov.io/bash) || echo 'Codecov did not collect coverage reports'
