sudo:
  - false
language:
  - python
os:
  - linux
python:
  - '2.6'
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7-dev'
cache:
  - pip
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=ebayfeed
after_success:
  - codecov
